### ISSUE TITLE
Redirection after successful form submission currently doesn't work if used with Django CMS.

### ISSUE THREAD

**Issue by samluescher** [samluescher/django-form-designer#1]

**Comment by rubytastic** [comment]
This bug still around?

**Comment by samluescher** [comment]
Yes, there's a dependency on a CMS issue that is still open: http://github.com/digi604/django-cms-2.0/issues/79

**Comment by DaveWP** [comment]
Any update on the resolution?  The referenced page in the above URL does not work!

**Comment by samluescher** [comment]
Project was renamed: http://github.com/divio/django-cms/issues/79
It seems there's no a resolution yet.

**Comment by samluescher** [comment]
Closed since Django CMS closed it.
