### ISSUE TITLE
No pt_BR translation

### ISSUE THREAD

**Issue by italomaia** [samluescher/django-form-designer#13]
# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR EMAIL@ADDRESS, YEAR.
# 

msgid ""
msgstr ""
"Project-Id-Version: PACKAGE VERSION\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2010-04-23 04:52-0300\n"
"PO-Revision-Date: YEAR-MO-DA HO:MI+ZONE\n"
"Last-Translator: FULL NAME EMAIL@ADDRESS\n"
"Language-Team: LANGUAGE LL@li.org\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
# : admin.py:15

msgid "This field class requires a model."
msgstr "A classe deste campo exige um modelo"
# : admin.py:23 admin.py:66

msgid "Basic"
msgstr "Básico"
# : admin.py:24

msgid "Display"
msgstr "Display"
# : admin.py:25 defaults.py:4

msgid "Text"
msgstr "Texto"
# : admin.py:26

msgid "Numbers"
msgstr "Números"
# : admin.py:27 defaults.py:17

msgid "Regex"
msgstr "Exp. regular"
# : admin.py:28

msgid "Choices"
msgstr "Escolhas"
# : admin.py:29

msgid "Model Choices"
msgstr "Modelos p/ escolha"
# : admin.py:67

msgid "Mail form"
msgstr "Formulário de email"
# : admin.py:68

msgid "Templates"
msgstr "Modelos"
# : admin.py:69

msgid "Messages"
msgstr "Mensagens"
# : admin.py:87 admin_views.py:36 cms_plugins.py:10 models.py:31 models.py:119
# : models.py:255

msgid "Form"
msgstr "Formulário"
# : admin.py:92 models.py:120

msgid "Data"
msgstr "Dado"
# : admin.py:104

msgid "CSV export is not enabled."
msgstr "Exportação p/ CSV não habilitada."
# : admin_views.py:38 models.py:118

msgid "Created"
msgstr "Criado"
# : admin_views.py:40

msgid "ID"
msgstr "ID"
# : defaults.py:5

msgid "E-mail address"
msgstr "Endereço de email"
# : defaults.py:6

msgid "Web address"
msgstr "Endereço web"
# : defaults.py:7

msgid "Number"
msgstr "Número"
# : defaults.py:8

msgid "Decimal number"
msgstr "Número decimal"
# : defaults.py:9

msgid "Yes/No"
msgstr "Sim/Não"
# : defaults.py:10

msgid "Date"
msgstr "Data"
# : defaults.py:11

msgid "Date & time"
msgstr "Data e tempo"
# : defaults.py:12

msgid "Time"
msgstr "Tempo"
# : defaults.py:13

msgid "Choice"
msgstr "Escolha"
# : defaults.py:14

msgid "Multiple Choice"
msgstr "Múltipla escolha"
# : defaults.py:15

msgid "Model Choice"
msgstr "Modelo p/ escolha"
# : defaults.py:16

msgid "Model Multiple Choice"
msgstr "Modelo p/ múltipla escolha"
# : defaults.py:21 defaults.py:28

msgid "Default"
msgstr "Padrão"
# : defaults.py:22

msgid "Text area"
msgstr "Área de texto"
# : defaults.py:23

msgid "Password input"
msgstr "Campo de senha"
# : defaults.py:24

msgid "Hidden input"
msgstr "Campo escondido"
# : defaults.py:29

msgid "as paragraphs"
msgstr "como parágrafos"
# : defaults.py:30

msgid "as table"
msgstr "como tabela"
# : models.py:13 models.py:133

msgid "Name"
msgstr "Nome"
# : models.py:14

msgid "Title"
msgstr "Título"
# : models.py:15

msgid "Target URL"
msgstr "URL destino"
# : models.py:15

msgid ""
"If you leave this empty, the page where the form resides will be requested, "
"and you can use the mail form and logging features. You can also send data "
"to external sites: For instance, enter \"http://www.google.ch/search\" to "
"create a search form."
msgstr ""
"Se você deixar este campo vazio, a página onde o formulário reside será pedida,"
"e você pode usar o formulário de email e funcionalidade de registro. Você pode também"
"enviar dados para sites externos. Exemplo: entre com \"http://www.google.ch/search\" para"
"criar um formulário de busca."
# : models.py:16

msgid "Send form data to e-mail address"
msgstr "Enviar dados do formulário para um endereço de email"
# : models.py:17

msgid "Sender address"
msgstr "Endereço emissor"
# : models.py:18

msgid "e-Mail subject"
msgstr "Assunto do email"
# : models.py:19

msgid "Method"
msgstr "Método"
# : models.py:20

msgid "Success message"
msgstr "Mensagem de sucesso"
# : models.py:21

msgid "Error message"
msgstr "Mensagem de erro"
# : models.py:22

msgid "Submit button label"
msgstr "Etiqueta do botão de submissão"
# : models.py:23

msgid "Log form data"
msgstr "Armazenar dados de formulário"
# : models.py:23

msgid "Logs all form submissions to the database."
msgstr "Armazenar todos os formulários enviados ao banco."
# : models.py:24

msgid "Redirect after success"
msgstr "Redirecionar após sucesso"
# : models.py:24

msgid "You should install django_notify if you want to enable this."
msgstr "Você deve instalar o django_notify para habilitar esta função."
# : models.py:25

msgid "Clear form after success"
msgstr "Limpar formulário após sucesso"
# : models.py:26

msgid "Allow initial values via URL"
msgstr "Permitir valores iniciais por URL"
# : models.py:26

msgid ""
"If enabled, you can fill in form fields by adding them to the query string."
msgstr ""
"Se habilitado, você pode preencher campos do formulário adicionando-os à query string."
# : models.py:27

msgid "Message template"
msgstr "Mensagem de template"
# : models.py:27

msgid ""
"Available context: \"data\" (a list containing a dictionary for each form "
"field, each containing the elements \"name\", \"label\", \"value\")."
msgstr ""
"Available context: \"data\" (a list containing a dictionary for each form "
"field, each containing the elements \"name\", \"label\", \"value\")."
# : models.py:28

msgid "Form template"
msgstr "Template de formulário"
# : models.py:32

msgid "Forms"
msgstr "Formulários"
# : models.py:69 models.py:159 models.py:245

msgid "Fields"
msgstr "Campos"
# : models.py:123

msgid "Form log"
msgstr "Registro do formulário"
# : models.py:124

msgid "Form logs"
msgstr "Registros do formulário"
# : models.py:130

msgid "Field class"
msgstr "Classe do campo"
# : models.py:131

msgid "Position"
msgstr "Posição"
# : models.py:134

msgid "Label"
msgstr "Etiqueta"
# : models.py:135

msgid "Required"
msgstr "Requerido"
# : models.py:136

msgid "Include in result"
msgstr "Incluir no resultado"
# : models.py:137

msgid "Widget"
msgstr "Widget"
# : models.py:138

msgid "Initial value"
msgstr "Valor inicial"
# : models.py:139

msgid "Help text"
msgstr "Texto de ajuda"
# : models.py:141

msgid "Values"
msgstr "Valores"
# : models.py:141

msgid "One value per line"
msgstr "Um valor por linha"
# : models.py:142

msgid "Labels"
msgstr "Etiquetas"
# : models.py:142

msgid "One label per line"
msgstr "Uma etiqueta por linha"
# : models.py:144

msgid "Max. length"
msgstr "Comprimento máx."
# : models.py:145

msgid "Min. length"
msgstr "Comprimento min."
# : models.py:146

msgid "Max. value"
msgstr "Valor máx."
# : models.py:147

msgid "Min. value"
msgstr "Valor mín."
# : models.py:148

msgid "Max. digits"
msgstr "Máx. digitos"
# : models.py:149

msgid "Decimal places"
msgstr "Campos decimais"
# : models.py:151

msgid "Regular Expression"
msgstr "Expressão regular"
# : models.py:154

msgid "Data model"
msgstr "Modelo de dados"
# : models.py:155

msgid "Empty label"
msgstr "Etiqueta vazia"
# : models.py:158 models.py:244

msgid "Field"
msgstr "Campo"
# : views.py:28

msgid "Thank you, the data was submitted successfully."
msgstr "Obrigado, os dados foram submetidos com sucesso."
# : views.py:29

msgid "The data could not be submitted, please try again."
msgstr "Os dados não puderam ser enviados, por favor, tente novamente."
# : templates/admin/form_designer/formlog/change_list.html:9

msgid "Export CSV"
msgstr "Exportar CSV"
# : templates/html/formdefinition/forms/as_p.html:10
# : templates/html/formdefinition/forms/as_table.html:10

msgid "Submit"
msgstr "Enviar"
# : templatetags/friendly.py:16

msgid "yes"
msgstr "sim"
# : templatetags/friendly.py:16

msgid "no"
msgstr "não"

**Comment by italomaia** [comment]
Above is the pt_BR translation 99%

**Comment by samluescher** [comment]
Please fork and send a pull request when you've made progress
