### ISSUE TITLE
Structure of Message Template

### ISSUE THREAD

**Issue by DaveWP** [samluescher/django-form-designer#14]
Can someone provide some guidance notes/documentation in respect to what you can put in this field, or URL describing where it is documented.  I want to send a message with the content of the form for off-line processing so I want to include form fields in the message body (ideally structured as XML).

Thanks

Dave

**Comment by samluescher** [comment]
This should be easy. See the default message template that just generates a message like "Label: Value\nLabel: Value…", and you'll be able to create an XML template:

http://github.com/philomat/django-form-designer/blob/master/form_designer/templates/txt/formdefinition/data_message.txt
