### ISSUE TITLE
Custom widgets

### ISSUE THREAD

**Issue by bmeyer71** [samluescher/django-form-designer#15]
Is it possible to add custom widgets? Not necessarily through the Admin interface, even just in the defaults.py.
I have a popup calendar using jscal2 that I use with a custom form that I would like to be able to use through form designer.

Thanks
Bjorn

**Comment by samluescher** [comment]
Yes. Define the following setting in your settings.py:

```
FORM_DESIGNER_WIDGET_CLASSES = (
    ('', _('Default')),
    ('django.forms.widgets.Textarea', _('Text area')),
    ('django.forms.widgets.PasswordInput', _('Password input')),
    ('django.forms.widgets.HiddenInput', _('Hidden input')),
    ('django.forms.widgets.RadioSelect', _('Radio button')),
    ('your widget here', _('some custom widget')),
)
```
