### ISSUE TITLE
Django 1.2 CSRF support

### ISSUE THREAD

**Issue by aseering** [samluescher/django-form-designer#16]
The latest code seems to fail in Django 1.2 because of its CSRF changes.  It works again (on a simple test example) if I add "{% csrf_token %}" on the line right after the form tag in templates/html/formdefinition/forms/default.html, as suggested by the latest Django docs.  I believe this is a no-op for older Django versions, so it doesn't hurt to have it.  Would you consider adding it?

**Comment by samluescher** [comment]
Phew, finally merged!
