### ISSUE TITLE
django-captcha integration

### ISSUE THREAD

**Issue by digi604** [samluescher/django-form-designer#2]
we have a very similar internal app... and a spam prevention system was the first thing we needed to implement

**Comment by samluescher** [comment]
Agreed, this is top priority

**Comment by arcticlinux** [comment]
Has there been any action on this issue, I find myself about to implement recaptcha with form-designer

**Comment by samluescher** [comment]
Actually I think that since there are many Captcha solutions out there, you should just implement your own Captcha field using your system of choice, and add it to MEDIA_TREE_FIELD_CLASSES. I prefer to only use/implement the standard field classes that come with Django.
