### ISSUE TITLE
TemplateSyntaxError using DjangoCMS

### ISSUE THREAD

**Issue by robrocker7** [samluescher/django-form-designer#27]
After creating a form and adding it via DjangoCMS I am getting the following error.

_TemplateSyntaxError at /_
**Caught ValueError while rendering: dictionary update sequence element #1 has length 4; 2 is required**

I am willing to provide any information you would like me to send to help debug.

**Comment by fatbox** [comment]
We also just ran into this error and have fixed it in my fork. I will open a pull request in a moment.

**Comment by robrocker7** [comment]
Thanks fatbox.

**Comment by samluescher** [comment]
Thank you robrocker7 and fatbox.
