### ISSUE TITLE
question about base.html

### ISSUE THREAD

**Issue by domguard** [samluescher/django-form-designer#32]
Not an issue, rather a question

The included base.html template is overriding my site base.html template
I saw that when I deleted the `html/formdefinition/base.html`template, I got my base.html back

What is the best way to modify this without touching your application ?

**Comment by samluescher** [comment]
As long as you don't add "html/formdefinition/" to your TEMPLATE_DIRS, this template shouldn't override your base.html. Is that what you did? Because otherwise, the template name would be "html/formdefinition/base.html", so no overriding a template named "base.html" there.

**Comment by domguard** [comment]
No, templates are automatically found by the django.template.loaders.app_directories.Loader

But anyway I was wrong : the only thing I needed to override is `html/formdefinition/detail.html`, to change its reference to your base.html template and point it to mine. First line :

```
{% extends "base.html" %}
```

and now it works nice
