### ISSUE TITLE
Decimal validation fails

### ISSUE THREAD

**Issue by ghost** [samluescher/django-form-designer#35]
Thanks for this awesome app -- you just saved us about a month worth of development time.  

Ran into a bug with decimal validation, probably due to the fact that Decimal / Float comparison is unreliable, so a Decimal field with min val 1.5 and max val 100 will throw a validation error if you submit 30 via the form.

```
>>> from decimal import Decimal
>>> d = Decimal('30')
>>> d > 1.5
True
>>> d < 100.0
False
>>> s = str(100.0)
>>> d < Decimal(s)
True
```

**Comment by samluescher** [comment]
You're welcome! Please feel free to fork and submit pull requests with your improvements.

The problem you're mentioning seems to be a Python problem, and thus outside the scope of this app.

```
Python 2.5.6 (r256:88840, Jul 31 2011, 19:30:45) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> Decimal('30') < 100.0
False
```

BUT:

```
Python 2.7.2 (default, Sep 17 2011, 19:32:36) 
[GCC 4.2.1 (Based on Apple Inc. build 5658) (LLVM build 2335.15.00)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from decimal import Decimal
>>> Decimal('30') < 100.0
True
```

**Comment by ghost** [comment]
Argh.  Yeah, we'll have to fork -- it breaks in Python 2.6 as well, which is still very much a supported version for Django.  Looks like a really simple fix in FormDefinitionField.get_form_field_init_args(); I'll submit a pull request if it works out.

**Comment by samluescher** [comment]
Yes please -- Still, maybe this kind of problem should be taken on by Django itself -- form_designer just uses Django's DecimalField, and if that is broken, I'm not sure whether we should be patching it on the app level.
