### ISSUE TITLE
File upload field 

### ISSUE THREAD

**Issue by samluescher** [samluescher/django-form-designer#4]

**Comment by meirion** [comment]
This would be really handy. In the meanwhile what would be the recommended way of easily handling file uploads on a django form w/ django-cms?

**Comment by bartTC** [comment]
Is there a branch/fork providing this?

**Comment by bartTC** [comment]
There is one https://github.com/LUKKIEN/django-form-designer/commit/3c6e87ba214cb505f0b8b15fb6f7238a1c0260b1

**Comment by samluescher** [comment]
Phew. Finally merged!
