### ISSUE TITLE
error in migration file 0008

### ISSUE THREAD

**Issue by domguard** [samluescher/django-form-designer#51]
`django.db.utils.DatabaseError: column "data" of relation "form_designer_formlog" does not exist`

happens at :

```
line 34, in forwards
db.delete_column('form_designer_formlog', 'data')
```

I just did a fresh install and `manage.py migrate form_designer`

**Comment by fyaconiello** [comment]
I also recieved this error

**Comment by crooksey** [comment]
+1 To this as an outstanding issue

**Comment by lukemaxwell** [comment]
I'm also experiencing this issue

**Comment by romlok** [comment]
This seems to be because structure changes and data migration take place in the same migration - something the South documentation explicitly warns about... ಠ_ಠ

I've split them apart in raumkraut/django-form-designer@1e67fa755e16d5e216d9d1e31702eac2c6f1ff24 (0008 and 0008b), so you can cherry-pick that commit if you need to.

**Comment by kynan** [comment]
@Raumkraut I tried your fork and the error persists. I think your patch is broken, see my comment. I've pushed a fix as taarifa/django-form-designer@600d7e178e2ca659a37262e805f9899d65cd33fa.

**Comment by romlok** [comment]
Strangely (yet obviously), it worked for me with that line in - perhaps to do with my only using SQLite so far?

I see you've fixed it yourself, but there were some other problems (with going backwards) which I've just fixed (hopefully!) in Raumkraut/django-form-designer@c5359519cd2ec9a2c12f4e5785fe92d8c2c16289. This is branched from the original 0008-split, so you won't get any of my other changes/merges if you don't want them.

**Comment by kynan** [comment]
I should mention I haven't tried with SQLite, but only with postgres.
