### ISSUE TITLE
Instant Validations for Forms

### ISSUE THREAD

**Issue by ghost** [samluescher/django-form-designer#54]
Hello, i'm trying to make instant validations for a "create account" form but I can't find enough documentation related to django-form-designer. If you have information about this that you can supply me I'll be thankful! 

Greetings, 
Emily

**Comment by samluescher** [comment]
For User Account creation you might want to look into django.contrib.auth, django-form-designer is not really designed for that. Also, it does not have any build-in instant (XHR?) validation.
