### ISSUE TITLE
PyPI setup.py

### ISSUE THREAD

**Issue by wernight** [samluescher/django-form-designer#6]
Would be nice to have a `setup.py` like almost all Django apps and most Django-CMS plugins. This would allow to have it directly on PyPI like http://pypi.python.org/pypi/cmsplugin-youtube

The good is that installing it would then become

```
$ PIP install cmsplugin-form-designer
```

or

```
$ easy_install cmsplugin-form-designer
```

**Comment by digi604** [comment]
second this

**Comment by elpargo** [comment]
third

**Comment by samluescher** [comment]
setup.py exists

**Comment by elpargo** [comment]
Thanks !
