### ISSUE TITLE
Migrations require picklefield.

### ISSUE THREAD

**Issue by a7p** [samluescher/django-form-designer#60]
ValueError: Cannot import the required field 'picklefield.fields.PickledObjectField'

on
'manage.py migrate django-form-designer'

**Comment by jheld** [comment]
I get the same issue when:
python2.6 manage.py migrate form_designer

Is there a work-around?

**Comment by matinfo** [comment]
Are you added this dep "django-picklefield" ?

**Comment by samluescher** [comment]
This should be fixed
