### ISSUE TITLE
Add AJAX Support via jQuery

### ISSUE THREAD

**Issue by QueryClick** [samluescher/django-form-designer#9]
Would allow for excellent flexibility in form usage (pulling in forms via jQuery dialog() and axax())

Suggest best based on the Python snippet here: http://www.djangosnippets.org/snippets/992/

Have tried integrating snippet myself (body of the AJAX view processed in process_form after is_submit:, but passing attributes between detail Def & process_form proving tricky. AJAX returns a 500, HttpResponse object has no attribute update from detail else: result.update(...
- will keep working & post code if successful, but any tips on approach useful!

**Comment by samluescher** [comment]
Not sure what you are actually trying to do – I suppose you want to implement AJAX-based form submission/validation?

The snippet seems a bit funny. For one thing, you don't need to add extra fields or change the request URL to make it clear that the client is making an AJAX request. This is best determined using request.is_ajax:

http://docs.djangoproject.com/en/dev/ref/request-response/#django.http.HttpRequest.is_ajax

Then, in process_form(), you would probably have to change things to something like:

```
if is_submit:
    if form.is_valid():
        # Successful submission
        if not request.is_ajax and 'django_notify' in settings.INSTALLED_APPS:
            request.notifications.success(success_message)
        else:
            message = success_message
        if form_definition.log_data:
            form_definition.log(form)
        if form_definition.mail_to:
            form_definition.send_mail(form)
        if not request.is_ajax:
            if form_definition.success_redirect and not is_cms_plugin:
                # TODO Redirection does not work for cms plugin
                return HttpResponseRedirect(form_definition.action or '?')
            if form_definition.success_clear:
                form = DesignedForm(form_definition) # clear form
        else:
            # AJAX: success, return `message` as JSON response:
            ... 
    else:
        if not request.is_ajax and 'django_notify' in settings.INSTALLED_APPS:
            request.notifications.error(error_message)
        else:
            message = error_message
        if request.is_ajax:
            # AJAX: form invalid, return `message` and validation errors JSON response:
            ... 
```

**Comment by QueryClick** [comment]
Interesting, of course need to take notify into account.

Have it running with:

```
    #Is this an AJAX request?
    if request.is_ajax():
        #Validate the form
        clean = form.is_valid()
        #Create some dictionary elements to pass back to template
        rdict = {'bad':'false'}
        if not clean:
            rdict.update({'bad':'true'})
            d={}
            #A painful! way to extract the error messages.
            for e in form.errors.iteritems():
                d.update({e[0]:unicode(e[1])}) # e[0] is the id, unicode(e[1]) is the error HTML.
            #Pop that into the dictionary.
            rdict.update({'errs': d  })
        #Build our json response
        json = simplejson.dumps(rdict, ensure_ascii=False)
        #And send it off
        return HttpResponse( json, mimetype='application/javascript')
    #If it's not AJAX, back to normal form processing...
```

and edited def detail...

if isinstance(result, HttpResponseRedirect):
        return result
    else:
        #This is not thoroughly tested: used to allow AJAX Response to return.
        if isinstance(result, HttpResponse):
            return result
        else:
            #End Edit
            result.update({

And getting responses back, but need to test thoroughly.

The end goal is to use the form designer to add forms which are triggered in jQuery via dialog() so repeatedly used forms (like login, contact us, etc) can be popped up, filled in and submitted without leaving the page you're on. Without the AJAX functionality form errors aren't returned.

**Comment by samluescher** [comment]
Closing since it is not really an issue. Please feel free to fork and send a pull request when you've made progress.
