### ISSUE TITLE
send form email: [Errno 111] Connection refused in djangocms 3.x

### ISSUE THREAD

**Issue by creimers** [samluescher/django-form-designer#93]
This is most probably an ignorance issue on my side and most likely just a question:

Trying to send a form post as an email, I get this `[Errno 111] Connection refused` error. It also reads: `Error during template rendering`.

Without the email option, I can post the form no problem.

Is extra configuration needed to enable email sending?

django version is 1.6.8

**Comment by barseghyanartur** [comment]
@creimers 

See this http://stackoverflow.com/questions/5802189/django-errno-111-connection-refused

**Comment by creimers** [comment]
Thank you, very helpful.

Just like this: 

http://stackoverflow.com/questions/6367014/how-to-send-email-via-django

**Comment by creimers** [comment]
I think it wouldn't hurt to include basic email settings in the README. Since django-form-designer provides this email option.
