### ISSUE TITLE
NoReverseMatch Error

### ISSUE THREAD

**Issue by ghost** [samluescher/django-form-designer#94]
Installed this to test with Django-CMS. 

All installed fine, but when I create a form in Django Admin and click "View on site" I get the following error:

NoReverseMatch at /en/admin/r/36/1/

This might something stupid on my part so forgive me if this is not an issue. 

Any help would be appreciated though.

**Comment by GregorKopka** [comment]
Add the URLs to your URL conf. For instance, in order to make a form named example-form available under http://domain.com/forms/example-form, add the following line to your project's urls.py:

```
urlpatterns = patterns('',
    (r'^forms/', include('form_designer.urls')),
    ...
)
```
